Issue 58 プロフィール画面
megane-s/minshumi-frontend pull request #113
Opened 2023-12-15 00:30 UTC by daisonmeganes

## 目的・解決すること

close #58 

## 変更内容

プロフィール画面の追加

## 動作確認の手順と項目

http://localhost:3000/user/test-user-4
http://localhost:3000/art/test-art-4
http://localhost:3000/user/test-user-2
http://localhost:3000/art/test-art-1

## スクリーンショット
![スクリーンショット 2023-12-15 092250](https://github.com/megane-s/minshumi-frontend/assets/148510436/e11f36c4-c1df-47fc-95d7-1b37253bbcda)
![スクリーンショット 2023-12-15 092305](https://github.com/megane-s/minshumi-frontend/assets/148510436/a103e6cf-b2bd-44f9-99b7-643d1673f7d3)

## 自己評価

出来を10点満点で自己評価:

5点

- [x] 実装できたのでチェックして欲しい。
- [ ] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [x] その他（下に記入）
カルーセル未実装、名刺の表示未実装
## 備考

2023-12-15 00:41 UTC, daisonmeganes commented on src/app/user/[user_id]/CommentForm.tsx
> +export const CommentForm: FC<CommentFormProps> = ({ businessCardId, isLogin, loginUser }) => {
対応済みです

- [不要な定義を削除](https://github.com/megane-s/minshumi-frontend/pull/113/commits/ca7fb92fb243b7d57f9ca4de413c92306a5d40bb)

2023-12-15 00:41 UTC, daisonmeganes commented on src/app/user/[user_id]/CommentForm.tsx
> +export const CommentForm: FC<CommentFormProps> = ({ businessCardId, isLogin, loginUser }) => {
対応済みです

- [不要な定義を削除](https://github.com/megane-s/minshumi-frontend/pull/113/commits/ca7fb92fb243b7d57f9ca4de413c92306a5d40bb)

2023-12-15 03:14 UTC, TBSten requested changes
量多めですが対応お願いしまーす

2023-12-15 03:14 UTC, TBSten commented on src/app/user/[user_id]/LikeArtImage.tsx
> +            </Dialog>
ここも `ArtDetailDialog` みたいにコンポーネントに分割するとよさそう

2023-12-15 03:14 UTC, TBSten commented on src/app/user/[user_id]/actions.ts
> +    await follow(loginUserId, followUserId)
cancelの時と同じように `revalidatePath(`/user/${followUserId}`)` するほうがよさそう

2023-12-15 03:14 UTC, TBSten commented on src/app/user/[user_id]/page.tsx
> +const UserProfilePage = async ({ params }: PageProps) => {
📝
データ取得の見直しのissue(#100) でいい感じに分割する

2023-12-15 03:14 UTC, TBSten commented on src/app/user/[user_id]/page.tsx
> +                        {/* TODO コメントない時に表示される内容を改善 */}
📝
別issueでやる

2023-12-15 03:14 UTC, TBSten commented on src/businessCard/comment/getByBusinessCard.ts
> +        // TODO 作成日の新しい順で返すように
📝
これも別issueでやる

2023-12-15 03:14 UTC, TBSten commented on src/user/follow/cancel.ts
>  export const cancelFollow = async (by: UserId, followUser: UserId): Promise<void> => {
📝
ここら辺、followとcancelFollowで引数の順があってないの気になるのでリファクタリングしたい（別issue）

2023-12-18 03:11 UTC, TBSten commented on src/app/user/[user_id]/actions.ts
> +    await follow(loginUserId, followUserId)
というのはgetFollowingsの内容が変わるのでページの表示内容が変わる→revalidateする必要がありそう（フォローしてるしてないでボタンが切り替わるなどはすでにクライアント側で制御しているが、フォロワー数が変わらないバグの原因になりえるので）

2023-12-18 05:45 UTC, daisonmeganes commented on src/app/user/[user_id]/CommentListItem.tsx
> +    const handleGoodClick = async () => {
対応しました
- [useMutateを使ってトーストを出す](https://github.com/megane-s/minshumi-frontend/pull/113/commits/0e059da7b2d3e858fa6224b9aa1cf2c16973c9ab)

2023-12-18 05:45 UTC, daisonmeganes commented on src/app/user/[user_id]/FollowButton.tsx
> +    }
- 対応しました
[useMutateを使ってトーストを出す](https://github.com/megane-s/minshumi-frontend/pull/113/commits/0e059da7b2d3e858fa6224b9aa1cf2c16973c9ab)

2023-12-18 05:48 UTC, daisonmeganes commented on src/app/user/[user_id]/CommentListItem.tsx
> +                </Dialog>
- 対応しました
[deleteConfirmCommentDialogをコンポーネント化](https://github.com/megane-s/minshumi-frontend/pull/113/commits/731cbfafcafc687af7346ca03961098f96c81961)

2023-12-18 05:49 UTC, daisonmeganes commented on src/app/user/[user_id]/LikeArtImage.tsx
> +            </Dialog>
- 対応しました
[LikeArtImageのダイアログをコンポーネント化](https://github.com/megane-s/minshumi-frontend/pull/113/commits/f4c2e6d388780c598acf4a94b9564a2c321a00ff)

2023-12-18 05:51 UTC, daisonmeganes commented on src/app/user/[user_id]/actions.ts
> +    await follow(loginUserId, followUserId)
- 対応しました
[handleFollowにrevalidatePathの実装](https://github.com/megane-s/minshumi-frontend/pull/113/commits/1498d104a90fc040d0d4a2f4d650d9604bc7a44e)

2023-12-19 07:12 UTC, TBSten commented on src/app/user/[user_id]/CommentListItem.tsx
> +export const CommentListItem: FC<CommentListItemProps> = ({ comment, commentUser, defaultIsGooded, isLogin, loginUser }) => {
起票済み

#128

2023-12-19 07:17 UTC, TBSten commented on src/businessCard/comment/getByBusinessCard.ts
> +        // TODO 作成日の新しい順で返すように
起票済み
#130

2023-12-19 07:18 UTC, TBSten commented on src/user/follow/cancel.ts
>  export const cancelFollow = async (by: UserId, followUser: UserId): Promise<void> => {
起票済み
#131

2023-12-19 07:20 UTC, TBSten approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249587)

別issueでの対応が多めですが一旦よさそうですー

2023-12-19 07:20 UTC, merged