[Issue-37]404ページの実装
megane-s/minshumi-frontend pull request #216
Opened 2024-01-15 02:08 UTC by daisonmeganes

## 目的・解決すること

close #37

## 変更内容

## 動作確認の手順と項目
存在しないページに移動

## スクリーンショット
![スクリーンショット 2024-01-15 110441](https://github.com/megane-s/minshumi-frontend/assets/148510436/79d01f4f-8c13-4157-8d0a-4c768578a161)

## 自己評価

出来を10点満点で自己評価:

7点

- [x] 実装できたのでチェックして欲しい。
- [x] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [ ] その他（下に記入）

## 備考
画像の大きさはどうですか？

2024-01-15 03:00 UTC, TBSten requested changes
- [ ] テキストとボタンは中央ぞろえのほうが見栄えがよさそう
- [ ] エラーページなのでテキストの色に赤色を使ったほうがいいなとおもいます。

2024-01-15 03:05 UTC, TBSten commented on src/app/not-found.tsx
> +                height={800}
画像のheightも修正の余地あり

(元画像が1000x500で横幅800pxあれば十分そう)
```suggestion
                width={800}
                height={400}
```

2024-01-15 05:00 UTC, daisonmeganes commented
> * [x]  テキストとボタンは中央ぞろえのほうが見栄えがよさそう
> * [x]  エラーページなのでテキストの色に赤色を使ったほうがいいなとおもいます。
https://github.com/megane-s/minshumi-frontend/pull/216/commits/45e01427bee68b82a67d76063493b068d983886f
対応しました

2024-01-15 05:00 UTC, daisonmeganes commented on src/app/not-found.tsx
> +                height={800}
対応しました
https://github.com/megane-s/minshumi-frontend/pull/216/commits/45e01427bee68b82a67d76063493b068d983886f

2024-01-15 05:02 UTC, daisonmeganes reviewed
https://github.com/megane-s/minshumi-frontend/pull/216/commits/45e01427bee68b82a67d76063493b068d983886f
対応しました

2024-01-15 05:17 UTC, daisonmeganes commented
![スクリーンショット 2024-01-15 140643](https://github.com/megane-s/minshumi-frontend/assets/148510436/8b733b15-2488-4b18-ab47-36e4d4ec1534)

2024-01-15 22:17 UTC, TBSten commented
「指定されたページが見つかりません」と言うテキストが小さいので<PageTitle>コンポーネントを使って大きくして欲しいです🙏

2024-01-16 04:54 UTC, daisonmeganes commented
![スクリーンショット 2024-01-16 134848](https://github.com/megane-s/minshumi-frontend/assets/148510436/973eabc1-669d-4061-a160-f7a58fd94f7a)

2024-01-16 04:54 UTC, daisonmeganes commented
![スクリーンショット 2024-01-16 135130](https://github.com/megane-s/minshumi-frontend/assets/148510436/f4be9475-cd8f-40ba-a390-5c4f77fea1bd)

2024-01-16 06:49 UTC, TBSten approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8250928)

2024-01-16 06:49 UTC, merged