[Issue-129]各ページの0件表示
megane-s/minshumi-frontend pull request #252
Opened 2024-01-18 07:05 UTC by daisonmeganes

## 目的・解決すること

close #129 

## 変更内容
各ページの0件表示を実装しました

## 動作確認の手順と項目
0件にさせて表示させてみてください

## スクリーンショット
作品検索画面の検索結果
![スクリーンショット 2024-01-18 155743](https://github.com/megane-s/minshumi-frontend/assets/148510436/e7ae0f40-7b26-44a9-ba8c-f435b525e00f)
ユーザー検索画面の検索結果
![スクリーンショット 2024-01-18 155721](https://github.com/megane-s/minshumi-frontend/assets/148510436/a39b6103-99b1-48e0-b30c-017221ad6fe3)
各タグ画面の作品一覧
![スクリーンショット 2024-01-18 152834](https://github.com/megane-s/minshumi-frontend/assets/148510436/d02a9916-1dbd-4622-907d-46bef9f5914e)
プロフィール画面のコメント欄
![スクリーンショット 2024-01-18 153326](https://github.com/megane-s/minshumi-frontend/assets/148510436/7324f874-3512-436b-b924-6d27cd9f9c60)

## 自己評価

出来を10点満点で自己評価:

8点

- [x] 実装できたのでチェックして欲しい。
- [x] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [x] その他（下に記入）

## 備考
- 各タグ画面の作品一覧で0件だった場合
ユーザが作品を作成させるためにボタンを置いてみました。
(めったに見ない0件表示になりそうだけど)
![スクリーンショット 2024-01-18 160432](https://github.com/megane-s/minshumi-frontend/assets/148510436/5076ab01-2e0c-401a-84a1-952da3d8d826)
- 画像、文章の内容はどうでしょうか？

2024-01-18 12:18 UTC, TBSten commented
ちょっとレイアウトシフトが気になるが一旦スルー

#89 で対応したい

https://github.com/megane-s/minshumi-frontend/assets/81161390/c1955723-33f1-4388-8481-e4f5f8ee9220

2024-01-18 12:30 UTC, TBSten commented
> ユーザが作品を作成させるためにボタンを置いてみました。
> (めったに見ない0件表示になりそうだけど)

![非常に_良さげ](https://github.com/megane-s/minshumi-frontend/assets/81161390/014efd05-1a7a-4ccd-a742-4963692a2e29)

2024-01-18 12:40 UTC, TBSten commented
- 全体的に空白がなくて窮屈な印象を受けるのでページタイトル上下にmarginを追加してください。

2024-01-18 12:41 UTC, TBSten requested changes
カードとかで囲ってもいいのかなと思いました。

<img src="https://github.com/megane-s/minshumi-frontend/assets/81161390/fd912259-bff4-4da3-bd79-7590935bea45" alt="カードあり" width="300">

2024-01-18 15:31 UTC, TBSten commented
以下もお願いします

- プロフィール画面
  - アピール
  - 今見ている作品

<img width="500" alt="スクリーンショット 2024-01-19 0 27 08" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/820bb76f-2916-4169-9844-d70c07a5d58e">

- 設定画面
  - ユーザタブの名刺
  - アピール作品タブ
  - 今見ている作品タブ

<img width="500" alt="スクリーンショット 2024-01-19 0 31 13" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/089e50a3-be2b-4344-89a9-e30209e72f53">
<img width="500" alt="スクリーンショット 2024-01-19 0 31 16" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/861371b2-920d-4760-93bc-d878d944c180">
<img width="500" alt="スクリーンショット 2024-01-19 0 31 24" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/81cca4f7-8467-4b40-b2c4-d5670cd8cb12">

2024-01-22 03:07 UTC, daisonmeganes commented
> 以下もお願いします
> 
> * プロフィール画面
>   
>   * アピール
>   * 今見ている作品
> 
> <img alt="スクリーンショット 2024-01-19 0 27 08" width="500" src="https://private-user-images.githubusercontent.com/81161390/297794237-820bb76f-2916-4169-9844-d70c07a5d58e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODU0ODIsIm5iZiI6MTcwNTg4NTE4MiwicGF0aCI6Ii84MTE2MTM5MC8yOTc3OTQyMzctODIwYmI3NmYtMjkxNi00MTY5LTk4NDQtZDcwYzA3YTVkNThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNjFhZjNhZWQ4NTM4NWVjMmNkYzAwZGI0MGVjMjIyYzgwOTRmMmUxYmE0ODBmYzFiNzA0ZGUxZGE1Yzc5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9A12VaE2rSIKTcHFkq-Mq6K2z9Vz7cP4oW1MLWbJFlE">
> * 設定画面
>   
>   * ユーザタブの名刺
>   * アピール作品タブ
>   * 今見ている作品タブ
> 
> <img alt="スクリーンショット 2024-01-19 0 31 13" width="500" src="https://private-user-images.githubusercontent.com/81161390/297795442-089e50a3-be2b-4344-89a9-e30209e72f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODU0ODIsIm5iZiI6MTcwNTg4NTE4MiwicGF0aCI6Ii84MTE2MTM5MC8yOTc3OTU0NDItMDg5ZTUwYTMtYmUyYi00MzQ0LTg5YTktZTMwMjA5ZTcyZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNzY3YWUzZGQyZGNjNzM4ZGJjMzE3ZTRlM2EyOTgwNmVlZTcxZWViOWZiODAwYWI2NTMzMzVkNWVmNDM2NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vcg7RHZDeBXw9htVzCRZ8g8lUQ-DGGtKvsOo4wRx4EE">	<img alt="スクリーンショット 2024-01-19 0 31 16" width="500" src="https://private-user-images.githubusercontent.com/81161390/297795453-861371b2-920d-4760-93bc-d878d944c180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODU0ODIsIm5iZiI6MTcwNTg4NTE4MiwicGF0aCI6Ii84MTE2MTM5MC8yOTc3OTU0NTMtODYxMzcxYjItOTIwZC00NzYwLTkzYmMtZDg3OGQ5NDRjMTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZGZmY2Q4MDgyM2ViOTBlZjViMjM5ODY5YzJmNTc2ZTNhZDBmOWEwMDJlZTRhZDRkNmJkNDIzMzgxMjJmY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xF5RFA-b2ZVtMDHAI-dn4yMgYRpBWoNLK-h5gy90KYY">	<img alt="スクリーンショット 2024-01-19 0 31 24" width="500" src="https://private-user-images.githubusercontent.com/81161390/297795457-81cca4f7-8467-4b40-b2c4-d5670cd8cb12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODU0ODIsIm5iZiI6MTcwNTg4NTE4MiwicGF0aCI6Ii84MTE2MTM5MC8yOTc3OTU0NTctODFjY2E0ZjctODQ2Ny00YjQwLWIyYzQtZDU2NzBjZDhjYjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNTk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NGFiNzQ4YmM0NGIyNGQ4OWQwNTU1MmI2NzE2OTJlZWVhZjY3MjU1NTQ2YTJmMTAzN2RmNGNkOGUxZjI4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TicKlJpzxj7PnTMd8buXbo23IIkvcnxnmuioBDjUthM">

対応済みです

2024-01-22 03:13 UTC, TBSten approved these changes
画像などをコンポーネントにまとめると見栄えがいいなと思いましたが一旦LGTMですー！

![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8245765)

2024-01-22 03:22 UTC, merged