[issue-255] 色々修正
megane-s/minshumi-frontend pull request #257
Opened 2024-01-18 15:42 UTC by TBSten

## 目的・解決すること

close #255 

## 変更内容

- FollowInfoを呼び出すように修正
- パフォーマンスが良くなるようにファイルに分割

## 動作確認の手順と項目

- 未ログイン時・ログイン時・自分のプロフィールページの時にそれぞれ期待された内容が表示されるか？

## スクリーンショット

<img width="956" alt="スクリーンショット 2024-01-19 0 41 49" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/7dd0b39b-9a1f-40ba-8700-a64623d6e824">

## 自己評価

出来を10点満点で自己評価:

8点

- [x] 実装できたのでチェックして欲しい。
- [ ] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [ ] その他（下に記入）

## 備考

2024-01-18 15:43 UTC, TBSten commented on src/app/user/[user_id]/page.tsx
> +                <FollowInfo userId={user.id} />
📝
ここがいつの間にか消えていたっぽい

2024-01-18 15:43 UTC, TBSten commented
コミットメッセージがゴミなのはご愛嬌

- [色々修正](https://github.com/megane-s/minshumi-frontend/pull/257/commits/65409b51dd3eeef13889f772c3191b3819596b55)

2024-01-19 06:21 UTC, greenmeganes requested changes
未ログイン、ログイン時にフォローとフォロワーがプロフィールに表示されていない。

2024-01-20 07:59 UTC, TBSten commented
> 未ログイン、ログイン時にフォローとフォロワーがプロフィールに表示されていない。


| 未ログイン時 | ログイン時 |
|---|---|
| <img width="680" alt="スクリーンショット 2024-01-20 16 57 15" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/4f4513b2-8c13-43ec-8f8f-31c27b57b9ab"> | <img width="680" alt="スクリーンショット 2024-01-20 16 57 27" src="https://github.com/megane-s/minshumi-frontend/assets/81161390/04bf7e2f-06e4-4686-989d-d1257da0cd48"> |

そんなことなさそう...?

2024-01-20 08:19 UTC, merged