[Issue-319] 名刺、アピール登録修正
megane-s/minshumi-frontend pull request #344
Opened 2024-01-29 05:15 UTC by greenmeganes

## 目的・解決すること

close #319 

## 変更内容
- 名刺3で称号とタグを選択できないように修正
- アピール文が空の時はアピールできないように修正

## スクリーンショット
名刺3
![スクリーンショット 2024-01-29 115135](https://github.com/megane-s/minshumi-frontend/assets/148510481/85a8c982-87aa-4536-b155-97a890903847)

アピール登録
![スクリーンショット 2024-01-29 140843](https://github.com/megane-s/minshumi-frontend/assets/148510481/ec2f2cdd-93d2-4b4c-bde7-f0878f142796)
![スクリーンショット 2024-01-29 140851](https://github.com/megane-s/minshumi-frontend/assets/148510481/7757afdb-a6f3-43c9-b546-1457d42e4991)

## 自己評価

出来を10点満点で自己評価:

10点

- [x] 実装できたのでチェックして欲しい。
- [ ] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [ ] その他（下に記入）

## 備考

2024-01-29 05:25 UTC, TBSten commented on src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
> +                        {!isBusinessCard3 && (
type3だった時にInputWrapperも表示しないようにしてください。（"興味のあるタグ"というラベルのみ表示されていて不自然）

2024-01-29 05:34 UTC, TBSten requested changes
動作検証しましたー
指摘箇所以外の動作は良さそうです

2024-01-29 07:06 UTC, greenmeganes commented on src/app/businesscard/[businesscard_id]/edit/BusinessCardEditor.tsx
> +                        {!isBusinessCard3 && (
修正しました！

2024-01-30 03:45 UTC, TBSten approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8244753)

2024-01-30 03:49 UTC, TBSten commented
コンフリクト解消しました

2024-01-30 07:17 UTC, merged