[Issue 335]設定画面の名刺作成ボタン、アイコンの変更
megane-s/minshumi-frontend pull request #353
Opened 2024-01-30 06:49 UTC by daisonmeganes

## 目的・解決すること

close #335 

## 変更内容
表題通り

## スクリーンショット
名刺0件
![スクリーンショット 2024-01-30 145016](https://github.com/megane-s/minshumi-frontend/assets/148510436/da561259-cd03-429b-b93b-253572b6f3e6)
名刺がある
![スクリーンショット 2024-01-30 145048](https://github.com/megane-s/minshumi-frontend/assets/148510436/781c81e2-bb36-4798-a9a5-d0c86c3c403b)
アイコンの変更
![スクリーンショット 2024-01-30 154653](https://github.com/megane-s/minshumi-frontend/assets/148510436/9c608a58-579e-47d4-8de1-92ca7162e086)

## 自己評価

出来を10点満点で自己評価:

7点

- [x] 実装できたのでチェックして欲しい。
- [x] 心配なところがいくつかある。
- [ ] あまり理解できていないがissueなどに書いてあるとおり やった。
- [ ] その他（下に記入）

## 備考
名刺作成ボタンの位置はどうですか？

2024-01-30 07:19 UTC, greenmeganes approved these changes
いいと思います。

2024-01-31 02:20 UTC, TBSten requested changes
> 名刺0件
> ![image](https://github.com/megane-s/minshumi-frontend/assets/81161390/b02084b9-997c-41a0-9cc4-fd4a1865ec96)

これだけだと一回作ってしまうと作成ボタンがなくなってしまうので、「名刺」というテキストの横において欲しいです。
というか名刺作成ボタンが下にあるのが違和感だったのでそれを上にしようみたいな話だったはず

<details>
<summary>イメージ</summary>

![ユーザ](https://github.com/megane-s/minshumi-frontend/assets/81161390/385def2f-a8f3-4d17-b0cb-9d5363ec28c2)


</details>

2024-01-31 02:24 UTC, TBSten commented
あとボタンは横に置くのは不自然なので下に置いて欲しいです

<details>
<summary>イメージ</summary>

![ユーザ (1)](https://github.com/megane-s/minshumi-frontend/assets/81161390/d86f12c9-338c-4404-b8bf-e9c151189128)

</details>

2024-01-31 02:25 UTC, TBSten requested changes
アイコンの方は良さそう。
名刺のボタンの位置の修正お願いします

2024-01-31 14:14 UTC, TBSten commented on src/app/settings/user/UserSettingForm.tsx
> +                                <Space h="0.5em" />
divタグにmy: "md" とかつけるだけでもいいけどこれでも良さそう。

2024-01-31 14:15 UTC, TBSten approved these changes
![LGTM](https://storage.googleapis.com/lgtm-ea733.appspot.com/lgtm/8249585)

2024-01-31 14:15 UTC, merged